name = "Photometry"
uuid = "af68cb61-81ac-52ed-8703-edc140936be4"
authors = ["Miles Lucas <mdlucas@hawaii.edu>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1"
DataFrames = "0.20"
Reexport = "0.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
